require:
- 'rspec-documentation/rubocop'
- 'rubocop-rake'
- 'rubocop-rspec'

AllCops:
  NewCops: enable
  Exclude:
  - 'spec/fixtures/**/*'
  - 'lib/rspec_documentation/page_tree.rb' # Rubocop bug, fixed in main
