# frozen_string_literal: true

module RSpecDocumentation
  # Configures the rspec-documentation gem, allows setting a context that makes values available to each example.
  class Configuration
    attr_reader :hooks

    def initialize
      @context_defined = false
      @hooks = {}
    end

    def context_defined?
      @context_defined
    end

    def attribution
      return @attribution if defined?(@attribution)

      'Documentation generated by ' \
        '<a target="_blank" href="https://github.com/bobf/rspec-documentation">rspec-documentation</a>'
    end

    def context(&block)
      raise Error, 'RSpecDocumentation context has already been defined.' if context_defined?

      @context_defined = true
      ::RSpec.shared_context('__rspec_documentation', &block)
    end

    def hook(name, &block)
      hooks[name] = block
    end
  end
end
